os: osx
language: ruby
cache: bundler

before_install:
- brew update
- brew audit ./homebrew/apache-arrow.rb
script:
- brew install -v --build-from-source --HEAD ./homebrew/apache-arrow.rb
- brew test ./homebrew/apache-arrow.rb
