os: osx
language: ruby
cache: bundler

before_install:
- brew update
script:
- brew audit ./apache-arrow.rb
- brew install -v --build-from-source --HEAD ./apache-arrow.rb
- brew test ./apache-arrow.rb
