# Inspired by https://github.com/gemnasium/homebrew-gemnasium/blob/master/.travis.yml
language: ruby
cache: bundler

before_install:
- brew update
install:
- mkdir -p $(brew --repo)/Library/Taps/travis
- ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
- brew tap --repair
env:
- PACKAGE=apache-arrow
script:
- brew audit $PACKAGE
- brew install -v --build-from-source $PACKAGE
- brew test $PACKAGE
