os: osx
language: ruby
cache: bundler

before_install:
- brew update
env:
- PACKAGE=apache-arrow
script:
- brew audit $PACKAGE
- brew install -v --build-from-source ./${PACKAGE}.rb
- brew test $PACKAGE
